language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules

#before_deploy:
#  - npm install serverless -g
#
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: serverless deploy
#  on:
#    branch: master
